// Assignment Code
var generateBtn = document.querySelector("#generate");

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;
}

// TODO: Write code so the generatePassword returns a string for a password
// which meets the requirements in the instructions.
function generatePassword() {
  return "";
}








//getRandomValues generated by the following four functions, console.logs to verfy results         

function getRandomLower() {
  return String.fromCharCode(Math.floor(Math.random()* 26) + 97);
}

console.log(getRandomLower());

//getRandomUpper
function getRandomUpper () {
  return String.fromCharCode(Math.floor(Math.random()* 26) + 65);
}

console.log(getRandomUpper());

//getRandomNumber
function getRandomNumber () {
  return String.fromCharCode(Math.floor(Math.random()* 10) + 48);
}

console.log(getRandomNumber());

//getRandomSymbol
function getRandomSymbol () {
  var symbols = "!@#$%^&*()_+{}|:<>?/.,;\][=-";
  return symbols[Math.floor(Math.random()* symbols.length)];
}

console.log(getRandomSymbol());




// generate random values upperCase, lowerCase, numbers, symbols
// lowerCase and numbers using .fromCharCode(#)
// for lowerCase,  
// String.fromCharCode(#), string aspect concecrates all # values together 
// using Math.floor(Math.random()*26) + 97 
// Math.floor sets random to whole numbers
// *26 makes specifies the range
// + 97 changes starting point by 97
// for upperCase
// +65 changes starting point 
// for getRandomSymbols, set var = to symbols
// in return use symbols[]
// Math.floor(Math.random()* symbols.length)
// multiply by symbols.length so random circulates and picks one of the many index values.
